create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  year integer,
  grade text default '',
  variant text default '',
  type text default 'Other',
  price numeric(12,2) not null default 0,
  mileage integer,
  image_url text default '',
  is_featured boolean not null default false,
  status text not null default 'AVAILABLE',
  location text default '',
  units integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  company_name text not null default 'Izuwan Automobile',
  pricelist_date text default '22.6.26',
  processing_fee numeric(12,2) not null default 2800,
  registration_fee numeric(12,2) not null default 0,
  default_interest numeric(5,2) not null default 3.2,
  default_dsr integer not null default 60,
  whatsapp_number text default '',
  promotion_banner text default '',
  logo_url text default '',
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists public.salesmen (
  id bigint generated by default as identity primary key,
  name text not null,
  whatsapp text not null default '',
  branch text default '',
  role text default 'Sales Advisor',
  specialty text default '',
  photo_url text default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.inventory add column if not exists mileage integer;
alter table public.inventory add column if not exists year integer;
alter table public.inventory add column if not exists grade text default '';
alter table public.inventory add column if not exists image_url text default '';
alter table public.inventory add column if not exists is_featured boolean not null default false;
alter table public.salesmen add column if not exists role text default 'Sales Advisor';
alter table public.salesmen add column if not exists specialty text default '';
alter table public.salesmen add column if not exists photo_url text default '';

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  title text not null,
  kicker text default 'SPECIAL EVENT',
  subtitle text default '',
  description text default '',
  start_date date,
  end_date date,
  location text default '',
  cta_label text default 'WhatsApp untuk info lanjut',
  cta_message text default '',
  banner_url text default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  title text not null default 'Delivered by Izuwan',
  customer_name text default '',
  model text default '',
  location text default '',
  delivered_at date,
  caption text default '',
  photo_url text default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_events add column if not exists kicker text default 'SPECIAL EVENT';
alter table public.site_events add column if not exists subtitle text default '';
alter table public.site_events add column if not exists description text default '';
alter table public.site_events add column if not exists start_date date;
alter table public.site_events add column if not exists end_date date;
alter table public.site_events add column if not exists location text default '';
alter table public.site_events add column if not exists cta_label text default 'WhatsApp untuk info lanjut';
alter table public.site_events add column if not exists cta_message text default '';
alter table public.site_events add column if not exists banner_url text default '';
alter table public.site_events add column if not exists is_active boolean not null default true;
alter table public.site_events add column if not exists updated_at timestamptz not null default now();
alter table public.deliveries add column if not exists title text not null default 'Delivered by Izuwan';
alter table public.deliveries add column if not exists customer_name text default '';
alter table public.deliveries add column if not exists model text default '';
alter table public.deliveries add column if not exists location text default '';
alter table public.deliveries add column if not exists delivered_at date;
alter table public.deliveries add column if not exists caption text default '';
alter table public.deliveries add column if not exists photo_url text default '';
alter table public.deliveries add column if not exists sort_order integer not null default 0;
alter table public.deliveries add column if not exists is_active boolean not null default true;
alter table public.deliveries add column if not exists updated_at timestamptz not null default now();

alter table public.admin_users enable row level security;
alter table public.inventory enable row level security;
alter table public.site_settings enable row level security;
alter table public.salesmen enable row level security;
alter table public.site_events enable row level security;
alter table public.deliveries enable row level security;

drop policy if exists "Users read own admin status" on public.admin_users;
create policy "Users read own admin status"
on public.admin_users for select
using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

drop policy if exists "Public reads active inventory" on public.inventory;
create policy "Public reads active inventory"
on public.inventory for select
using (is_active = true or public.is_admin());

drop policy if exists "Admins manage inventory" on public.inventory;
create policy "Admins manage inventory"
on public.inventory for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public reads settings" on public.site_settings;
create policy "Public reads settings"
on public.site_settings for select
using (true);

drop policy if exists "Admins manage settings" on public.site_settings;
create policy "Admins manage settings"
on public.site_settings for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public reads active salesmen" on public.salesmen;
create policy "Public reads active salesmen"
on public.salesmen for select
using (is_active = true or public.is_admin());

drop policy if exists "Admins manage salesmen" on public.salesmen;
create policy "Admins manage salesmen"
on public.salesmen for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public reads active events" on public.site_events;
create policy "Public reads active events"
on public.site_events for select
using (is_active = true or public.is_admin());

drop policy if exists "Admins manage events" on public.site_events;
create policy "Admins manage events"
on public.site_events for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public reads active deliveries" on public.deliveries;
create policy "Public reads active deliveries"
on public.deliveries for select
using (is_active = true or public.is_admin());

drop policy if exists "Admins manage deliveries" on public.deliveries;
create policy "Admins manage deliveries"
on public.deliveries for all
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('branding', 'branding', true)
on conflict (id) do update set public = true;

drop policy if exists "Public reads branding" on storage.objects;
create policy "Public reads branding"
on storage.objects for select
using (bucket_id = 'branding');

drop policy if exists "Admins upload branding" on storage.objects;
create policy "Admins upload branding"
on storage.objects for insert
with check (bucket_id = 'branding' and public.is_admin());

drop policy if exists "Admins update branding" on storage.objects;
create policy "Admins update branding"
on storage.objects for update
using (bucket_id = 'branding' and public.is_admin());

drop policy if exists "Admins delete branding" on storage.objects;
create policy "Admins delete branding"
on storage.objects for delete
using (bucket_id = 'branding' and public.is_admin());

-- Selepas create user di Authentication > Users, jadikan user itu admin:
-- insert into public.admin_users (user_id) values ('PASTE-USER-UUID-HERE');
